# Generated by Django 5.2 on 2025-05-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_date_rating_created_at_alter_rating_dish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='date',
        ),
    ]
